Second Intake Merge
systemoverloadrobotics/Robot2022 pull request #11
Opened 2022-01-21 06:03 UTC by Basil070104

2022-01-21 06:08 UTC, baconstrip requested changes

2022-01-21 06:08 UTC, baconstrip commented on src/main/java/frc/robot/commands/IndexBall.java
> +    intake.toggleSolenoid();
This has the effect of rapidly toggling the intake back and forth, since you call this every scan.

2022-01-21 06:09 UTC, Basil070104 commented on src/main/java/frc/robot/commands/IndexBall.java
> +    intake.toggleSolenoid();
how should we do it so it doesn't toggle back and forth

2022-01-21 06:12 UTC, Basil070104 commented on src/main/java/frc/robot/commands/IndexBall.java
> +    intake.toggleSolenoid();
should i put the toggle method in the initialize method?

2022-01-22 07:34 UTC, baconstrip requested changes

2022-01-22 07:34 UTC, baconstrip commented on src/main/java/frc/robot/subsystems/Intake.java
>    public void stop() {
We shouldn't have two methods with different names that do the same thing, can we clean this up?

2022-01-22 07:34 UTC, baconstrip commented on src/main/java/frc/robot/RobotContainer.java
> +    Constants.Input.INTAKE_BUTTON.get().whenPressed(indexBall);
This will only run the command once when the button is pressed, which is not what we want here.

2022-01-24 12:34 UTC, baconstrip approved these changes

2022-01-24 12:34 UTC, merged