Swerve simplified
systemoverloadrobotics/Robot2022 pull request #14
Opened 2022-01-25 00:29 UTC by Basil070104

2022-01-27 11:00 UTC, baconstrip requested changes

2022-01-27 11:00 UTC, baconstrip commented on src/main/java/frc/robot/RobotContainer.java
> +
This code should definitely go elsewhere, it's pretty bulky for the RobotContainer.

2022-01-27 11:00 UTC, baconstrip commented on src/main/java/frc/robot/subsystems/Swerve.java
> +    new Thread(() -> {
Generally, we need to ensure that we practice thread safety if we are doing stuff like this. This can cause corruption.

What is the point of resetting this after a second, by the way?

2022-01-27 11:00 UTC, baconstrip commented on src/main/java/frc/robot/subsystems/Swerve.java
> +  public double getHeading(){
Since this is only used in one place, it should be folded into getrotation2d

2022-01-27 11:00 UTC, baconstrip commented on src/main/java/frc/robot/modules/SwerveModule.java
> +
We probably want to set minimums here as well, making sure we're not burning up the motors. 

For both steering and power.

2022-01-27 11:00 UTC, baconstrip commented on src/main/java/frc/robot/modules/SwerveModule.java
> +        steeringPIDController = new PIDController(Constants.PID.P_SWERVE, 0, 0);
We should probably use the integral PID control in the motor controller here.

2022-01-27 11:00 UTC, baconstrip commented on src/main/java/frc/robot/modules/SwerveModule.java
> +        powerController.set(ControlMode.PercentOutput, state.speedMetersPerSecond/ Constants.Motor.SWERVE_MAX_SPEED);
We should probably use the integral PID control in power as well.

2022-01-27 11:00 UTC, baconstrip commented on src/main/java/frc/robot/commands/SwerveDrive.java
> +    this.x2Supplier = x2Supplier;
if x2 is meant to be rotation, I think we should change it everywhere to "rotation" or "w" throughout, as this is pretty confusing.

Then we can drop the numbers after x and y.

2022-01-27 17:24 UTC, Basil070104 commented on src/main/java/frc/robot/RobotContainer.java
> +
fixed

2022-01-27 17:26 UTC, Basil070104 commented on src/main/java/frc/robot/subsystems/Swerve.java
> +  public double getHeading(){
fixed

2022-01-27 17:48 UTC, Basil070104 commented on src/main/java/frc/robot/commands/SwerveDrive.java
> +    this.x2Supplier = x2Supplier;
fixed

2022-01-27 18:23 UTC, Basil070104 commented on src/main/java/frc/robot/modules/SwerveModule.java
> +
fixed

2022-01-27 18:25 UTC, Basil070104 commented on src/main/java/frc/robot/modules/SwerveModule.java
> +        steeringPIDController = new PIDController(Constants.PID.P_SWERVE, 0, 0);
can we use a separate PID controller because it provide more useful methods than the one in-built.

2022-01-27 21:36 UTC, Basil070104 commented on src/main/java/frc/robot/modules/SwerveModule.java
> +        powerController.set(ControlMode.PercentOutput, state.speedMetersPerSecond/ Constants.Motor.SWERVE_MAX_SPEED);
How would we do this? Do I just creat a PID controller for the power controller also.

2022-01-27 21:42 UTC, Basil070104 commented on src/main/java/frc/robot/modules/SwerveModule.java
> +        steeringPIDController = new PIDController(Constants.PID.P_SWERVE, 0, 0);
oh, do you mean instead of a proportional control use the integral term?

2022-01-28 14:25 UTC, baconstrip commented on src/main/java/frc/robot/modules/SwerveModule.java
> +        steeringPIDController = new PIDController(Constants.PID.P_SWERVE, 0, 0);
The motor controller can manage this internally, using the control on the motor controller improves the quality of the response. 

See the docs here https://store.ctr-electronics.com/content/api/java/html/classcom_1_1ctre_1_1phoenix_1_1motorcontrol_1_1can_1_1_talon_s_r_x.html#af31fc29a9ccca041824760028b02ff03 , in particular using controlmode.POSITION.

By using POSITION, you just send the motor controller an encoder count to reach and it takes care of the rest.

2022-01-28 14:26 UTC, baconstrip commented on src/main/java/frc/robot/modules/SwerveModule.java
> +        powerController.set(ControlMode.PercentOutput, state.speedMetersPerSecond/ Constants.Motor.SWERVE_MAX_SPEED);
See comment above, but in velocity instead of position mode.

2022-01-28 14:27 UTC, baconstrip requested changes

2022-01-28 14:27 UTC, baconstrip commented on src/main/java/frc/robot/RobotContainer.java
> +
Unresolved.

2022-01-28 14:29 UTC, baconstrip commented
See also the official documentation here with documentation on how the integral closed loop control works.

https://docs.ctre-phoenix.com/en/stable/ch16_ClosedLoop.html

2022-01-28 19:26 UTC, Basil070104 commented on src/main/java/frc/robot/modules/SwerveModule.java
> +        powerController.set(ControlMode.PercentOutput, state.speedMetersPerSecond/ Constants.Motor.SWERVE_MAX_SPEED);
resolved

2022-01-28 19:26 UTC, Basil070104 commented on src/main/java/frc/robot/modules/SwerveModule.java
> +        steeringPIDController = new PIDController(Constants.PID.P_SWERVE, 0, 0);
resolved

2022-02-01 12:15 UTC, baconstrip commented on src/main/java/frc/robot/commands/SwerveDrive.java
> +    double x2speed = rotationSupplier.getAsDouble();
Renaming was missed here.

2022-02-01 23:15 UTC, Basil070104 commented on src/main/java/frc/robot/commands/SwerveDrive.java
> +    xLimiter = new SlewRateLimiter(Constants.Motor.SWERVE_MAX_SPEED);
are you talking about the maximum change in the rotationLimiter? cause I would assume for the xLimiter and yLimiter  you would use the max speed.

2022-02-02 04:33 UTC, Basil070104 commented on src/main/java/frc/robot/commands/auto/SwerveExampleAuto.java
> +  public Command executeAuto(){
resolved

2022-02-02 06:18 UTC, Basil070104 commented on src/main/java/frc/robot/commands/SwerveDrive.java
> +    xLimiter = new SlewRateLimiter(Constants.Motor.SWERVE_MAX_SPEED);
resolved

2022-02-02 12:05 UTC, baconstrip approved these changes

2022-02-02 12:05 UTC, merged