Storage Logic and Intake Buttons
systemoverloadrobotics/Robot2022 pull request #16
Opened 2022-02-02 07:23 UTC by Basil070104

2022-02-02 13:59 UTC, baconstrip requested changes

2022-02-02 13:59 UTC, baconstrip commented on src/main/java/frc/robot/subsystems/Storage.java
> +    feeder.set(0.5);
This should be a constant.

2022-02-02 13:59 UTC, baconstrip commented on src/main/java/frc/robot/subsystems/Storage.java
> +    }else{
formatting pls. Running the autoformatter in VSCode on all files should fix this.

2022-02-02 13:59 UTC, baconstrip commented on src/main/java/frc/robot/subsystems/Storage.java
> +      movementBelt.set(ControlMode.Position, -0.75);
These number should be constants

2022-02-02 13:59 UTC, baconstrip commented on src/main/java/frc/robot/subsystems/Storage.java
> +    proximitySensor[0] = intakeSensor;
We probably don't need this array, and leaking the indicies out of this class (as with the detectBall method below) is an abstraction violation. That method should take an enum of sensors, or it should be three separate methods, but as it stands, this is not a good way of abstracting out the concept.

2022-02-02 13:59 UTC, baconstrip commented on src/main/java/frc/robot/subsystems/Intake.java
> +    intake.set(ControlMode.PercentOutput, -0.5);
This should be a constant

2022-02-02 13:59 UTC, baconstrip commented on src/main/java/frc/robot/commands/IntakeBall.java
> +    intake.toggleSolenoid();
Not that this is likely to happen, but we should probably make this an explicit "turn on," so that it doesn't get backwards, just in case.

2022-02-02 13:59 UTC, baconstrip commented on src/main/java/frc/robot/commands/IndexBall.java
> +    if(storage.detectBall(0)){
This will only run the belt until the ball is out of the way of the sensor, which is not the intent. 

I think the easiest way to do this would be to chain commands, and see if WPILib has something like "commandUntil" and make the condition triggering the other sensor, or something.

2022-02-02 19:08 UTC, Basil070104 commented on src/main/java/frc/robot/Constants.java
> +    public static final double P_FEEDER = 0.7;
we can put the other factors in later. I just put it as a placeholder. we can definitely use the other when we start testing

2022-02-02 19:22 UTC, Basil070104 commented on src/main/java/frc/robot/commands/IndexBall.java
> +    if(storage.detectBall(0)){
yeah i think there is. i might just extend a sequential command group on index ball and create other commands to be controlled by sensor feedback than

2022-02-03 21:07 UTC, Basil070104 commented on src/main/java/frc/robot/commands/IndexBall.java
> +    if(storage.detectBall(0)){
i tried something that you can look at

2022-02-16 07:37 UTC, baconstrip commented
Can you rebase this so I can review?

2022-03-01 19:15 UTC, merged