finished the climb command subsystem
systemoverloadrobotics/Robot2022 pull request #9
Opened 2022-01-17 04:46 UTC by ychhatre

2022-01-17 08:51 UTC, baconstrip commented on src/main/java/frc/robot/modules/ClimbModule.java
> +		spark.set(0.5);
This should be in the constants.

2022-01-17 08:51 UTC, baconstrip commented on src/main/java/frc/robot/commands/ClimbCommand.java
> +		if (this.isClimbing) {
This has the effect of constantly restarting the timer while the button is held. 

Instead we should probably use sensor feedback to know when we're on the bar and when to stop climbing.

2022-01-17 08:51 UTC, baconstrip commented on src/main/java/frc/robot/modules/ClimbModule.java
> +		spark.stopMotor();
This stops the motor every time this method is run.

2022-01-19 06:19 UTC, ychhatre commented on src/main/java/frc/robot/modules/ClimbModule.java
> +public class ClimbModule {
fixed

2022-01-19 06:22 UTC, ychhatre commented on src/main/java/frc/robot/modules/ClimbModule.java
> +		spark.set(0.5);
fixed

2022-01-19 07:07 UTC, baconstrip commented on src/main/java/frc/robot/commands/ClimbCommand.java
> +	public void execute() {
Since we're using motor controllers with integrated closed-loop control (PID), we should instead do something like:

```
climb.setSetpoint(Constants.CLIMB_TARGET_SETPOINT);
else {
  climb.stop();
  }
  ```

2022-01-19 07:07 UTC, baconstrip commented on src/main/java/frc/robot/subsystems/Climb.java
> +	// public Climb() {
Delete commented code before merging.

2022-01-19 07:07 UTC, baconstrip commented on src/main/java/frc/robot/subsystems/Climb.java
> +	private CANSparkMax rightClimbMotor;
Prefer something like "climb" and "climbFollower" or "mainMotor" and "follower," there's no inherent sidedness to the climber.

2022-01-19 07:07 UTC, baconstrip commented on src/main/java/frc/robot/subsystems/Climb.java
> +	private RelativeEncoder leftEncoder;
Same as above.

2022-01-19 07:07 UTC, baconstrip commented on src/main/java/frc/robot/subsystems/Climb.java
> +		leftClimbMotor.stopMotor();
This motor will never turn, you're calling stopMotor()

2022-01-20 00:44 UTC, baconstrip requested changes

2022-01-20 00:44 UTC, baconstrip commented on src/main/java/frc/robot/subsystems/Climb.java
> +			mainMotor.set(Constants.MotorSettings.MOTOR_VELOCITY);
We need to do closed loop control here, making sure that we're aiming for a set point.

Also the else clause here is going to cause the mechanism to violently oscillate

2022-01-21 05:40 UTC, baconstrip approved these changes

2022-01-21 05:40 UTC, merged